services:
  server-management-fe:
    image: ghcr.io/andreejait/server-management-fe:latest
    container_name: server-management-fe
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080}